### ISSUE TITLE
Read the docs.

### ISSUE THREAD

**Issue by jason-neal** [iastro-pt/ObservationTools#12]
I have started a branch to add a read the docs documentation for this project. 

[Its](https://observationtools.readthedocs.io/en/documentation/) just a table of contents atm but am working on it.

**Comment by DanielAndreasen** [comment]
Nice, let us know if you need some help.

**Comment by jason-neal** [comment]
I have scraped home page text and the installation guide from the `README.md` file.

I also worked on the page for `visibility.py`, pulling examples from the PR.
Let me know (or make the changes yourself) if there is more that should be added there.

I do need to replace the image for the `starobs` example as the title is cut off.

Updated version can be found at the same link.
