### ISSUE TITLE
Indexerror in airmass formating.

### ISSUE THREAD

**Issue by jason-neal** [iastro-pt/ObservationTools#13]
I re-cloned the master branch just now and tried running
```python visibility.py HD41248,HD219828 -s esolasilla -d 2016-04-04```
And got the following issue:
```
Calculating visibility for HD41248,HD219828
2016-04-04
La Silla Observatory
Traceback (most recent call last):
  File "visibility.py", line 559, in <module>
    VisibilityPlot(date=date, targets=targets, observatory=args.site)
  File "visibility.py", line 418, in VisibilityPlot
    for t in range(airmass2.size): airmassformat.append("{0:2.2f}".format(airmass2[t]))
IndexError: too many indices for array
```
It even fails for a single target and default settings.
The python version I am using is  `Python 3.5.2` and `PyA 0.10.1`.

The `starobs` mode 
```python visibility.py HD967,HD22879,HD40865 -m starobs
```
did manage to run and plot though (narrows down issue).

**Comment by DanielAndreasen** [comment]
Maybe PR #11 broke this? I can try to run it tomorrow without the formatting if I remember.

**Comment by jason-neal** [comment]
Maybe, thanks. If only there had been automatic PR tests....

**Comment by jason-neal** [comment]
I think it is a python3 related error.  If I change to a py2.7 environment it seemed to work fine...

I tried rolling back some commits with py3 but was still receiving the error well before #11

**Comment by DanielAndreasen** [comment]
Problem was that in python3, when using `map`, the result will not be a list. This has been fixed.
