### ISSUE TITLE
Independent y-axis centered on a common value.

### ISSUE THREAD

**Issue by jason-neal** [iastro-pt/ObservationTools#14]
I have working on script to do rv plotting on [this branch](https://github.com/jason-neal/ObservationTools/tree/RV)

I am using twinx() to place the rv of the start and its companion on a separate y-axis. 
I want to include a line at the mean_value (system offset) but the two curves are not centered, as shown by the two horizontal lines.

![time_curve](https://cloud.githubusercontent.com/assets/10076879/25597751/8b861580-2ec8-11e7-9480-1000613fc356.png)

How would I align both axis to be centered on the particular rv value the value? (Leaving 1 horizontal line)
 Each axis would still need independent scaling as the rv amplitudes are not the same.

**Comment by DanielAndreasen** [comment]
I had a quick look. Can you explain why you want the two y-axis to be on a different scale?
The solution is to do something like this (I just invent some functions, but I think it is clear what they do):

    K1, K2 = get_amplitudes()  # Get the two amplitude of the orbit
    gamma = get_system_velocity()
    # Do the plotting part
    ax1.set_ylim(gamma-K1*1.1, gamma+K1*1.1)
    ax2.set_ylim(gamma-K2*1.1, gamma+K2*1.1)

**Comment by jason-neal** [comment]
Thanks the code worked well to center the two plots.

The relative amplitude of the two curves is related to the mass ratio between the star and companion.
Therefore for large ratios the star rv curve becomes hard to see compared to the companion.

Centering these lines may have uncovered a separate issue in my RV curves. The peaks of the curves were cut off indicating that their value is `> gamma +/- K_`. Which shouldn't happen if `RV = gamma + K * sin(...)`.  I will add some tests of this to find the issue.

**Comment by DanielAndreasen** [comment]
You can also just use 1.5 instead of 1.1. In any case, you are moving forward.

**Comment by jason-neal** [comment]
Yes I did move to a value of 1.5 and it looked fine. I am just not confident about the rv values now.

**Comment by DanielAndreasen** [comment]
I understand, but I think that is without the scope of this issue. Can we close it?

**Comment by jason-neal** [comment]
Turns out  was thinking of the 0 eccentricity case, which is a simple the sine/cosine.
