### ISSUE TITLE
Artifact at end of nighttime. Inconsistency in Starobs for "today". 

### ISSUE THREAD

**Issue by jason-neal** [iastro-pt/ObservationTools#15]
I was randomly trying visibility.py calls to test #13 and I came across this strange example.

There seems to be an issue with the ending of the night time. (I assume the line is linking to values below the plot) 
```
python visibility.py HD4747
```
Which should be reproducible via.
```
python visibility.py HD4747 -d "2017-05-02-13-20-10"   # Hack in the time.
```
![python_visibility_py_hd4747](https://cloud.githubusercontent.com/assets/10076879/25617286/79051886-2f39-11e7-8c93-f0e8e37bc6d0.png)

If I specify todays date with `-d` I get
```
python visibility.py HD4747 -d "2017-05-02"
```
![python_visibility_py_hd4747-d_2017-05-02](https://cloud.githubusercontent.com/assets/10076879/25617287/79075f6a-2f39-11e7-9ccd-6cc5b7ca8a25.png)

I believe that the automatic date generation for 'today' should strip out the HH:MM:SS values from datetime.now() to have consistency, between a specified day and the datetime.now(). This will make the time scale consitant I assume.

I think fixing the datetime would hide the artifact in the first image above. BUT I think the issue could still be present and could possibly manifest for high latitude observatories, in which there are two periods of darkness in a day. I am not sure.

I am sure there is probably an easy way to not join lines between "disconnected" sections. 
- A hack could be to maybe include a NAN between the values.  
- Or more simply. We could just change the linestyle to dots like the daytime.

**Comment by DanielAndreasen** [comment]
I've seen this before, but didn't investigate it further. Changing the linestyle seems to be this simpliest option, if it works.

**Comment by j-faria** [comment]
I also noticed this problem before (the plot artifact, not the inconsistency with today) but honestly I was lazy to fix it. A better solution would be to just plot the night part... But that would need more stuff like checking sunset, sunrise hours...

**Comment by jason-neal** [comment]
Very well then.
This issue is at least a record incase someone else comes across it and/or wants to fix it...

**Comment by jason-neal** [comment]
Excellent! Both issues seem to be addressed.

The hack (hidden feature) -d "YYYY-mm-dd-HH-MM-SS"  is even still possible if you want to specify time for some reason (e.g. this plot to check against the first.) or maybe if you didn't like the peaks being cut off at the edges.

![py_visibility_fixed](https://cloud.githubusercontent.com/assets/10076879/25622192/89a26114-2f4b-11e7-9f9a-6ef30d68a34b.png)


Great job.

**Comment by DanielAndreasen** [comment]
A great team effort 😄
