### ISSUE TITLE
Installation issues (requires numpy) 

### ISSUE THREAD

**Issue by jason-neal** [iastro-pt/ObservationTools#8]
Hi, I tried cloning this to work on it in a new conda environment.
Running the command 
`pip install -r requirements.txt ` 
results in ...
> Collecting PyAstronomy (from -r requirements.txt (line 5))
>   Using cached PyAstronomy-0.10.1.tar.gz
>     Complete output from command python setup.py egg_info:
>     Please install 'numpy' first.
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-wM5T99/PyAstronomy/setup.py", line 153, in <module>
>         class WithExtCommand(Command):
>     NameError: name 'Command' is not defined
> 

It seems PyAstronomy needs numpy to be installed properly.  I tried reordering the requirements.txt file so PyAstronomy was last but that did not solve the issue. It downloads them all first before installing. 

I don't know if there is an automatic fix to this solution to this other than running
`pip install numpy ` first. (which works).

**Comment by jason-neal** [comment]
No because PyAstronomy is not in conda I think.

```
conda create  -n new_env --file requirements.txt  
Fetching package metadata .......
Solving package specifications: .
Error: Package missing in current linux-64 channels: 
  - pyastronomy

You can search for packages on anaconda.org with

    anaconda search -t conda pyastronomy

```

**Comment by DanielAndreasen** [comment]
Maybe I do something wrong, but when I run `conda create -n name; source activate name` this enviroment has all the packages installed from my root enviroment...

I don't think this is a big concern as most people who might use this will have numpy installed. But let's fix it anyway.

**Comment by jason-neal** [comment]
I did a quick google search and [this thread](https://stackoverflow.com/questions/5394356/how-to-specify-install-order-for-python-pip) has some solutions.

Basically you need to download/build/install one at a time using something like
 `xargs -L 1 pip install < requirements.txt`  
-L1 specifies that it only reads( and installs) one line at a time from requirements.

Maybe this can be added to the README.

**Comment by DanielAndreasen** [comment]
Better to just make a `Makefile` for this.

**Comment by jason-neal** [comment]
Yea I checked and I don't have PyAstronomy in my root conda. The installation did work if there was already built/cached versions of the packages known to pip.

**Comment by DanielAndreasen** [comment]
Maybe this can be a solution: https://github.com/pypa/pipfile

**Comment by jason-neal** [comment]
This is the result of https://github.com/pypa/pip/issues/25 which is a common issue.
I have opened https://github.com/sczesla/PyAstronomy/issues/22 to fix pyastronomy's setup.py file.

**Comment by j-faria** [comment]
Wondering if https://github.com/sdispater/poet would solve this...

**Comment by jason-neal** [comment]
I tested it and it still gives same error. Neat project though. Yet another way to package python....

Simplified the problem is the pyastronomy setup.py file has a bare `import numpy....` call. This is run by pip when searching all the requirements to find all the dependencies to install. Since it has not installed numpy yet it fails. Hopefully it can be changed on pyastronomy's side and the problem will disappear.

**Comment by jason-neal** [comment]
I have added a version dependence in the requirements.txt file for version pyastronomy>=0.11. The recent 0.11 release resolved the issue discussed here.
